language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install arguable
  - haxelib install utest
  - haxelib install buddy
  - git clone https://github.com/dpeek/hx-semver
  - haxelib dev hx-semver hx-semver/src

script:
  - make run-test
